package cluster

const (
	MULTI_PART = 0x8000

	REQUEST_SINGLE_NUMBER uint8 = 0x00
	REQUEST_SINGLE_STRING uint8 = 0x80

	REQUEST_MULTI_NUMBER      uint8 = 0x01
	REQUEST_MULTI_NUMBER_PUSH uint8 = 0x41

	REQUEST_MULTI_STRING      uint8 = 0x81
	REQUEST_MULTI_STRING_PUSH uint8 = 0xc1

	REQUEST_MULTI_PART     uint8 = 0x02
	REQUEST_MULTI_PART_END uint8 = 0x03

	REQUEST_TRACE uint8 = 0x04

	DEFAULT_BUFFER_SIZE = 0x8200
)

const (
	RESPONSE_ERROR       uint8 = 0
	RESPONSE_OK          uint8 = 1
	RESPONSE_MULTI_BEGIN uint8 = 2
	RESPONSE_MULTI_PART  uint8 = 3
	RESPONSE_MULTI_END   uint8 = 4
	RESPONSE_END         uint8 = 5
)
